import { createRoot } from "react-dom/client";
import { ReportAdminDashboard } from "./report-admin-dashboard";
import { MAIN_APP_ORIGIN } from "@/shared/admin-site";
import "@/packages/web/src/styles/globals.css";
import "@/packages/web/src/styles/earning-report.css";
import "@/packages/web/src/report/report-blocks/report-content.css";
import "@/packages/web/src/report/figures/figures.css";
import "katex/dist/katex.min.css";
import "@/packages/web/src/styles/spontra-ui.css";
import "./report-admin.css";
createRoot(document.getElementById("root")!).render(<ReportAdminDashboard mainAppOrigin={MAIN_APP_ORIGIN} />);
