import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

// Run against the local dev server. All admin requests use an isolated migrated
// SQLite backend and a recorded Workflow binding; no production reads or writes.
await mkdir('outputs/report-admin', { recursive: true });
import { chromium } from '@playwright/test';
import { createAnalysisDatabase } from './pipeline/helpers/analysis-backend.ts';
import { seedAnalysisFixtures, FIXTURE_TICKER, VERIFIED_ACCESSION } from './pipeline/helpers/analysis-fixtures.ts';
import { handleReportAdminRequest } from '../workers/pipeline/src/admin/reports.ts';
import { handleReportAdminProxy } from '../lib/report-admin-proxy.ts';
import type { SecCronEnv, SecWorkflowParams } from '../workers/pipeline/src/core.ts';

const database = await createAnalysisDatabase(); await seedAnalysisFixtures(database);
const jobs: Array<{id:string;params:SecWorkflowParams}> = [];
const now=Date.parse('2026-10-02T01:42:00Z');
const secret='local-browser-test-admin-key';
const d1={prepare(sql:string){return {bind(...args:unknown[]){const s=database.prepare(sql).bind(...args);return {first:s.first.bind(s),all:s.all.bind(s),async run(){const r=await s.run() as {changes:number};return {meta:{changes:Number(r.changes)}};}};}};}};
const env:SecCronEnv={DB:d1 as unknown as D1Database,SEC_REFRESH_KEY:secret,SEC_TRACKED_TICKERS:FIXTURE_TICKER,SEC_ANALYSIS_WORKFLOW:{async create(o){jobs.push(o);return {id:o.id};}}};
await database.prepare('INSERT INTO sec_cache (cache_key,payload,fetched_at) VALUES (?,?,?)').bind('sec:filings:MSFT',JSON.stringify({company:{name:'微软',ticker:'MSFT',cik:'0000789019'},filings:[],fetchedAt:new Date(now).toISOString()}),new Date(now).toISOString()).run();
const raw=database.raw.prepare('SELECT payload FROM sec_filing_summaries WHERE accession_number=?').get(VERIFIED_ACCESSION) as {payload:string};
const summary=JSON.parse(raw.payload);
summary.headline='微软财报分析'; summary.generatedAt='2026-10-02T01:42:00Z';
summary.bullets=[{label:'经营表现',detail:'本期收入和利润持续增长。核对收入的业务结构、增长驱动和利润变化，关注现金流能否支撑资本投入。',importance:'high'},{label:'风险与关注点',detail:'资本开支增长可能影响自由现金流，应回到原始申报材料核对管理层对未来投入的说明。',importance:'high'}];
summary.analystView='结合财报披露与已核验数据评估增长质量，持续跟踪业务变化。';
summary.report='本期经营表现延续增长趋势。收入变化应结合业务分部、计量口径与会计期间进行判断。\n\n现金流与利润可能因营运资金变化而出现差异，建议结合现金流量表核对。';
database.raw.prepare('UPDATE sec_filing_summaries SET payload=? WHERE accession_number=?').run(JSON.stringify(summary),VERIFIED_ACCESSION);
const transport={EARNING_REPORT_PIPELINE:{fetch:async(input:RequestInfo|URL,options?:RequestInit)=>handleReportAdminRequest(new Request(input,options),env,now)}};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1024}});
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://images.financialmodelingprep.com/**',route=>route.abort());
await page.route('**/api/admin/**',async route=>{const r=route.request();const parts=new URL(r.url()).pathname.slice('/api/admin/'.length).split('/').map(decodeURIComponent);const init:RequestInit={method:r.method(),headers:r.headers()};if(r.method()!=='GET')init.body=r.postData()??undefined;const response=await handleReportAdminProxy(new Request(r.url(),init),parts,transport);await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:await response.text()});});
await page.goto('http://localhost:4173/admin/reports');
await page.getByLabel('管理密钥',{exact:true}).waitFor();
await page.screenshot({path:'outputs/report-admin/login.png'});
await page.getByLabel('管理密钥',{exact:true}).fill(secret);
await page.getByRole('button',{name:'登录后台',exact:true}).click();
await page.getByRole('heading',{name:'微软 · 财报分析'}).waitFor();
await page.screenshot({path:'outputs/report-admin/desktop-before.png'});
assert.equal(await page.evaluate(()=>location.pathname),'/admin/reports');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.getByRole('button',{name:'标记已检查',exact:true}).click();
await page.getByRole('button',{name:'已检查',exact:true}).waitFor();
await page.getByRole('button',{name:'重新生成',exact:true}).click();
await page.getByRole('dialog').waitFor();
await page.screenshot({path:'outputs/report-admin/regenerate-confirm.png'});
await page.getByRole('button',{name:'取消',exact:true}).click();assert.equal(jobs.length,0);
await page.getByRole('button',{name:'重新生成',exact:true}).click();
await page.getByRole('button',{name:'确认重新生成',exact:true}).click();
await page.getByText('重新生成任务已提交。完成后可查看新版本，当前报告会保留。',{exact:true}).waitFor();
assert.equal(jobs.length,1);assert.equal(jobs[0].params.accessionNumber,VERIFIED_ACCESSION);assert.equal(jobs[0].params.regenerateReport,true);
await page.getByRole('button',{name:'正在生成',exact:true}).waitFor();
assert.equal(await page.getByRole('button',{name:'正在生成',exact:true}).isDisabled(),true);
await page.screenshot({path:'outputs/report-admin/history.png'});
await page.getByRole('tab',{name:'报告内容',exact:true}).click();
await page.getByLabel('搜索公司或报告').fill('no-such-company');await page.getByText('没有符合条件的报告',{exact:true}).waitFor();
await page.getByLabel('搜索公司或报告').fill('MSFT');await page.getByRole('heading',{name:'微软 · 财报分析'}).waitFor();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'outputs/report-admin/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.setViewportSize({width:1440,height:1024});
assert.deepEqual(errors,[]);
console.log('PASS: login, authenticated real-SQL report list/detail, persistent review, regeneration cancel/confirm, correct filing identity, duplicate prevention, search/empty state, stable URL, desktop/mobile overflow, zero browser exceptions.');
await browser.close();database.close();
