/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/sec-cron/wrangler.jsonc --include-runtime=false --env-interface=PortfolioSyncBindings workers/sec-cron/worker-configuration.d.ts` (hash: afcf4ea5ec93244d36e68d3a8f2b5bad)
interface __BaseEnv_PortfolioSyncBindings {
	DB: D1Database;
	IBKR_FLEX_QUERY_ID: "1628251";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_PortfolioSyncBindings {}
}
interface PortfolioSyncBindings extends __BaseEnv_PortfolioSyncBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IBKR_FLEX_QUERY_ID">> {}
}
