/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/pipeline/wrangler.jsonc --include-runtime=false workers/pipeline/worker-configuration.d.ts` (hash: 7cb1a40bd5597ac65b8acf1881449617)
interface __BaseEnv_Env {
	SEC_FILINGS: R2Bucket;
	DB: D1Database;
	REPORT_ADMIN_RATE_LIMIT: RateLimit;
	SEC_BUSINESS_FLOW_BOOTSTRAP_TICKERS: "ORCL";
	SEC_DATA_TICKERS: "ORCL,NVDA,MSFT,AAPL,JPM,BRK.B,ADSK,NET";
	SEC_AI_TICKERS: "ORCL,ADSK,NET";
	SEC_AI_ENABLED: "true";
	SEC_DATA_COLLECTION_ENABLED: "true";
	SEC_USER_AGENT: "earning-report-analysis/1.0 max.zhangyuchen@gmail.com";
	SEC_ANALYSIS_MODEL: "deepseek-flash";
	SEC_REASONING_MODEL: "deepseek-flash";
	GUIDANCE_ENABLED: "true";
	FINDINGS_ENABLED: "true";
	GUIDANCE_DECK_SEARCH: "true";
	GUIDANCE_DAILY_MODEL_CALLS: "40";
	GUIDANCE_DAILY_TRANSCRIPT_CALLS: "25";
	TRANSCRIPTS_ENABLED: "true";
	DEEPSEEK_API_KEY: string;
	GUIDANCE_WORKFLOW: Workflow<Parameters<import("./src/index").GuidanceWorkflow['run']>[0]['payload']>;
	BUSINESS_EXPLAINER_WORKFLOW: Workflow<Parameters<import("./src/index").BusinessExplainerWorkflow['run']>[0]['payload']>;
	FINDINGS_WORKFLOW: Workflow<Parameters<import("./src/index").FindingsWorkflow['run']>[0]['payload']>;
	SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").SecAnalysisWorkflow['run']>[0]['payload']>;
	SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./src/index").SecMemoryWorkflow['run']>[0]['payload']>;
	COMPANY_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").CompanyAnalysisWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEC_BUSINESS_FLOW_BOOTSTRAP_TICKERS" | "SEC_DATA_TICKERS" | "SEC_AI_TICKERS" | "SEC_AI_ENABLED" | "SEC_DATA_COLLECTION_ENABLED" | "SEC_USER_AGENT" | "SEC_ANALYSIS_MODEL" | "SEC_REASONING_MODEL" | "GUIDANCE_ENABLED" | "FINDINGS_ENABLED" | "GUIDANCE_DECK_SEARCH" | "GUIDANCE_DAILY_MODEL_CALLS" | "GUIDANCE_DAILY_TRANSCRIPT_CALLS" | "TRANSCRIPTS_ENABLED" | "DEEPSEEK_API_KEY">> {}
}
