export const flexFixture = [
  '"HEADER","ACCT","ClientAccountID","CurrencyPrimary","DateFunded"',
  '"DATA","ACCT","ACCOUNT","USD","20260101"',
  '"HEADER","CTRN","ClientAccountID","CurrencyPrimary","FXRateToBase","Type","Amount","TransactionID","ReportDate","LevelOfDetail"',
  '"DATA","CTRN","ACCOUNT","USD","1","Deposits/Withdrawals","1000","deposit1","20261201","DETAIL"',
  '"HEADER","TRFR","ClientAccountID","ReportDate","LevelOfDetail","TransactionID","FXRateToBase","CashTransfer","PositionAmountInBase"',
  '"HEADER","EQUT","ClientAccountID","ReportDate","Total"',
  '"DATA","EQUT","ACCOUNT","20261231","70000.50"',
  '"HEADER","CRTT","ClientAccountID","CurrencyPrimary","LevelOfDetail","ToDate","EndingCash","FromDate","Deposit/Withdrawals","AccountTransfers","InternalTransfers","PaxosTransfers"',
  '"DATA","CRTT","ACCOUNT","USD","BaseCurrency","20261231","12000.25","20260101","1000","0","0","0"',
  '"HEADER","POST","ClientAccountID","CurrencyPrimary","AssetClass","Symbol","Description","Conid","UnderlyingSymbol","Multiplier","ReportDate","Quantity","MarkPrice","PositionValue","CostBasisPrice","CostBasisMoney","FifoPnlUnrealized","LevelOfDetail"',
  '"DATA","POST","ACCOUNT","USD","STK","ACME","ACME, INC","123","","1","20261231","10","20","200","15","150","50","SUMMARY"',
  '"DATA","POST","ACCOUNT","USD","STK","ACME","ACME, INC","123","","1","20261231","6","20","120","14","84","36","LOT"',
  '"DATA","POST","ACCOUNT","USD","STK","ACME","ACME, INC","123","","1","20261231","4","20","80","16.5","66","14","LOT"',
  '"HEADER","TRNT","ClientAccountID","CurrencyPrimary","AssetClass","Symbol","Description","UnderlyingSymbol","TradeID","DateTime","TradeDate","Exchange","Quantity","TradePrice","IBCommission","NetCash","FifoPnlRealized","Buy/Sell","IBOrderID","LevelOfDetail"',
  '"DATA","TRNT","ACCOUNT","USD","STK","ACME","ACME, INC","","trade-summary","","20261231","","10","20","0","0","0","","","SYMBOL_SUMMARY"',
  '"DATA","TRNT","ACCOUNT","USD","STK","ACME","ACME, INC","","trade-1","20261231;233000 EST","20261231","NYSE","2","20","-0.35","-40.35","5.25","SELL","88","EXECUTION"',
].join("\n");
